---
title: "COVID-19 Global Pandemic"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(shiny)
library(httr)
library(jsonlite)
```

```{r COVID-19 summary, include=FALSE}
# Import data.
COVID <- read.csv("WHO-COVID-19-global-table-data.csv")

# The global stats for total cumulative cases and per 100k population and total cumulative deaths and per 100k population
COVID_global <- COVID %>%
  arrange(desc(Cases...cumulative.total)) %>% 
  head(1)

# Create a subset of COVID dataset to include necessary variables such as Name, Who.Region, Cases...cumulative.total.per.100000.population,
# and Deaths...cumulative.total.per.100000.population and rename the variables.
COVID_clean <- COVID %>% 
  select(Name, WHO.Region, 
         Cases.Cumulative.Per.100k = Cases...cumulative.total.per.100000.population, 
         Deaths.Cumulative.Per.100k = Deaths...cumulative.total.per.100000.population)

```

COVID-19 Summary
=======================================================================

Row {data-height=50}
-----------------------------------------------------------------------

The COVID-19 summary encompasses data from 241 countries, offering a comprehensive overview of the most recent reported numbers of COVID-19 cases and deaths, as sourced from the World Health Organization (WHO). This summary provides a global perspective on the pandemic's impact, highlighting the spread and mortality.

Row {data-height=125}
-----------------------------------------------------------------------

### Total Cases

```{r valueboxes_total_case}
valueBox(value = "775,867,542",
         caption = "Total Global Cases",
         icon = "ion-thermometer",
         color = "#b3cde0")

```

### Total Cases per 100k Population  

```{r valueboxes_total_cases_per_100k}
valueBox(value = "4,798,837",
         caption = "Total Global Cases per 100k Population",
         icon = "ion-thermometer",
         color = "#b3cde0")

```

Row {data-height=450}
-----------------------------------------------------------------------

### High Spread Countries

```{r high spread countries}
# Select three countries from the top 10 countries with the highest number of total cases per 100K population.
# Arrange the Cases.Cumulative.Per.100k column from descending and isolate the top 10 countries. 
COVID_high_spread <- COVID_clean %>%
  arrange(desc(Cases.Cumulative.Per.100k)) %>% 
  head(11) # Filter for the top 11 entries because Global is also included in the top Cases.Cumulative.Per.100k.

# The countries selected to represent the countries with the highest number of total cases per 100k population are 
# Cyprus, Austria and Republic of Korea.
COVID_high_spread <- COVID_high_spread %>%
  filter(Name %in% c("Cyprus", "Austria", "Republic of Korea"))

# Plot the countries with one of the highest number of total cases per 100k population. 
ggplot(COVID_high_spread, aes(x = Name, y = Cases.Cumulative.Per.100k)) +
  geom_bar(stat = "identity", fill = "#005b96") +
  labs(title = "High Spread Countries",
       x = "Country",
       y = "Cumulative Cases Per 100K Population") +
  ylim(0, 80000) +
  theme_minimal()
```

### Low Spread Countries

```{r low spread countries}
# Select three other countries where number of total cases per 100K population is less than 10,000.
# Filter Cases.Cumulative.Per.100k with less than 10000 cases and arrange in descending order.
COVID_low_spread <- COVID_clean %>%
  filter(Cases.Cumulative.Per.100k < 10000) %>%
  arrange(desc(Cases.Cumulative.Per.100k))

# The countries selected to represent the countries with <10,000 cases per 100k population are 
# Cuba, Guyana, Iran.
COVID_low_spread <- COVID_low_spread %>%
  filter(Name %in% c("Cuba", "Guyana", "Iran (Islamic Republic of)"))

# Plot the countries with <10k total cases per 100k population.
ggplot(COVID_low_spread, aes(x = Name, y = Cases.Cumulative.Per.100k)) +
  geom_bar(stat = "identity", fill = "#005b96") +
  labs(title = "Low Spread Countries",
       x = "Country",
       y = "Cumulative Cases Per 100K Population") +
  ylim(0, 80000) +
  theme_minimal()
```

Row {data-height=125}
-----------------------------------------------------------------------

### Total Deaths

```{r valueboxes_total_deaths}
valueBox(value = "7,057,145",
         caption = "Total Global Deaths",
         icon = "ion-alert-circled",
         color = "#b3cde0")

```

### Total Deaths per 100k Population  

```{r valueboxes_total_deaths_per_100k}
valueBox(value = "29,394",
         caption = "Total Global Deaths per 100k Population",
         icon = "ion-alert-circled",
         color = "#b3cde0")

```

Row {data-height=450}
-----------------------------------------------------------------------

### High Mortality Countries 

```{r high mortality countries}
# Select three countries from the top 10 countries with the highest number of total deaths per 100K population.
# Arrange the Deaths.Cumulative.Per.100k column from descending and isolate the top 10 countries. 
COVID_high_mortality <- COVID_clean %>%
  arrange(desc(Deaths.Cumulative.Per.100k)) %>% 
  head(11) # Filter for the top 11 entries because Global is also included in the top Deaths.Cumulative.Per.100k

# The countries selected to represent the countries with the highest number of total deaths per 100k population are 
# Peru, Hungary, and Bosnia and Herzegovina. 
COVID_high_mortality <- COVID_high_mortality %>%
  filter(Name %in% c("Peru", "Hungary", "Bosnia and Herzegovina"))

# Plot the countries with one of the highest number of total death per 100k population. 
ggplot(COVID_high_mortality, aes(x = Name, y = Deaths.Cumulative.Per.100k)) +
  geom_bar(stat = "identity", fill = "#005b96") +
  labs(title = "High Mortality Countries",
       x = "Country",
       y = "Cumulative Deaths Per 100K Population") +
  ylim(0, 800) +
  theme_minimal()
```

### Low Mortality Countries 

```{r low mortality countries}

# Select three other countries where number of total deaths per 100K population is less than 250. 
# Filter Deaths.Cumulative.Per.100k with less than 250 deaths and arrange in descending order.
COVID_low_mortality <- COVID_clean %>%
  filter(Deaths.Cumulative.Per.100k < 250) %>%
  arrange(desc(Deaths.Cumulative.Per.100k))

# The countries selected to represent the countries with <10,000 deaths per 100k population are 
# Guam, Bahamas, Germany
COVID_low_mortality <- COVID_low_mortality %>% 
  filter(Name %in% c("Guam", "Bahamas", "Germany"))

# Plot the countries with <10k total death per 100k population.
ggplot(COVID_low_mortality, aes(x = Name, y = Deaths.Cumulative.Per.100k)) +
  geom_bar(stat = "identity", fill = "#005b96") +
  labs(title = "Low Mortality Countries",
       x = "Country",
       y = "Cumulative Deaths Per 100K Population") +
  ylim(0, 800) +
  theme_minimal()
```

Socioeconomic Indicators
=======================================================================

```{r API}
# Extract demographic and socioeconomic indicator from World Bank API
# Build query
base <- "https://api.worldbank.org/v2"
endpoint <- "/country/AUT;KOR;CYP;GUY;CUB;IRN;PER;HUN;BIH;BHS;DEU;GUM"
query <- "/indicator/SP.POP.TOTL;EN.POP.DNST;NY.GDP.MKTP.CD;NY.GNP.MKTP.CD;SP.DYN.LE00.IN;SI.POV.NAHC;SI.POV.GINI;SE.ADT.LITR.ZS;NY.ADJ.NNTY.PC.CD;SP.DYN.CBRT.IN;SP.DYN.CDRT.IN;SP.POP.GROW;SP.URB.TOTL.IN.ZS;SP.RUR.TOTL.ZS"
output_format <- "?format=json&per_page=5000&date=2020:2022&source=2"

# Combine all parts of the query to produce a call
call <- paste0(base, endpoint, query, output_format)

# Get info from call and check status
get_data <- GET(call)

# Extract content from the request
get_data_text <- content(get_data, "text")

# Convert JSON file into an R object
get_data_json <- fromJSON(get_data_text, flatten = T)

# Converted information to dataframe
socioecon_df <- get_data_json[2][[1]]

# Renamed column names and select relevant columns
socioecon_df <- socioecon_df %>% rename(
  country_iso = countryiso3code,
  year = date,
  socioecon_id = indicator.id,
  socioecon_indicator = indicator.value,
  country = country.value
) %>% select(country, country_iso, year, socioecon_id, socioecon_indicator, value)

```

### NAME

```{r}

#gameplan 
# make a dataset for each indicator
# group by country 

# Use a fluid Bootstrap layout
ui <- fluidPage(    
  
  # Give the page a title
  titlePanel("Population by Country"),
  
  # Generate a row with a sidebar
  sidebarLayout(      
    
    # Define the sidebar with one input
    sidebarPanel(
      selectInput("country", "Country:", 
                  choices= unique(socioecon_df$country)),
      hr(),
      helpText("Data from World Bank Group (2022).")
    ),
    
    # Create a spot for the barplot
    mainPanel(
      plotOutput("countryPlot")  
    )
    
  )
)

# Define a server for the Shiny app
server <- function(input, output) {
  # Fill in the spot we created for a plot
  output$phonePlot <- renderPlot({
    
    # Render a barplot
    barplot(WorldPhones[,input$region]*1000, 
            main=input$region,
            ylab="Year",
            xlab="Population Size")
  })
}

shinyApp(ui, server)

```







