---
title: "COVID-19 Global Pandemic"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(httr)
library(jsonlite)
library(plotly)
library(DT)
```

```{r COVID-19 Summary, include=FALSE}
# Import data.
COVID <- read.csv("WHO-COVID-19-global-table-data.csv")

# The global stats for total cumulative cases and per 100k population and total cumulative deaths and per 100k population
COVID_global <- COVID %>%
  arrange(desc(Cases...cumulative.total)) %>% 
  head(1)

# Create a subset of COVID dataset to include necessary variables such as Name, Who.Region, Cases...cumulative.total.per.100000.population,
# and Deaths...cumulative.total.per.100000.population and rename the variables.
COVID_clean <- COVID %>% 
  select(Name, WHO.Region, 
         Cases.Cumulative.Per.100k = Cases...cumulative.total.per.100000.population, 
         Deaths.Cumulative.Per.100k = Deaths...cumulative.total.per.100000.population)

```

COVID-19 Summary
=======================================================================

Row {data-height=50}
-----------------------------------------------------------------------

The COVID-19 summary encompasses data from 241 countries, offering a comprehensive overview of the most recent reported numbers of COVID-19 cases and deaths, as sourced from the World Health Organization (WHO). This summary provides a global perspective on the pandemic's impact, highlighting the spread and mortality.

Row {data-height=125}
-----------------------------------------------------------------------

### Total Cases

```{r valueboxes_total_case}
valueBox(value = "775,867,542",
         caption = "Total Global Cases",
         icon = "ion-thermometer",
         color = "#b3cde0")

```

### Total Cases per 100k Population  

```{r valueboxes_total_cases_per_100k}
valueBox(value = "4,798,837",
         caption = "Total Global Cases per 100k Population",
         icon = "ion-thermometer",
         color = "#b3cde0")

```

Row {data-height=450}
-----------------------------------------------------------------------

### High Spread Countries

```{r high spread countries}
# Select three countries from the top 10 countries with the highest number of total cases per 100K population.
# Arrange the Cases.Cumulative.Per.100k column from descending and isolate the top 10 countries. 
COVID_high_spread <- COVID_clean %>%
  arrange(desc(Cases.Cumulative.Per.100k)) %>% 
  head(11) # Filter for the top 11 entries because Global is also included in the top Cases.Cumulative.Per.100k.

# The countries selected to represent the countries with the highest number of total cases per 100k population are 
# Cyprus, Austria and Republic of Korea.
COVID_high_spread <- COVID_high_spread %>%
  filter(Name %in% c("Cyprus", "Austria", "Republic of Korea"))

# Plot the countries with one of the highest number of total cases per 100k population. 
ggplot(COVID_high_spread, aes(x = Name, y = Cases.Cumulative.Per.100k)) +
  geom_bar(stat = "identity", fill = "#005b96") +
  labs(title = "High Spread Countries",
       x = "Country",
       y = "Cumulative Cases Per 100K Population") +
  ylim(0, 80000) +
  theme_minimal()
```

### Low Spread Countries

```{r low spread countries}
# Select three other countries where number of total cases per 100K population is less than 10,000.
# Filter Cases.Cumulative.Per.100k with less than 10000 cases and arrange in descending order.
COVID_low_spread <- COVID_clean %>%
  filter(Cases.Cumulative.Per.100k < 10000) %>%
  arrange(desc(Cases.Cumulative.Per.100k))

# The countries selected to represent the countries with <10,000 cases per 100k population are 
# Cuba, Guyana, Iran.
COVID_low_spread <- COVID_low_spread %>%
  filter(Name %in% c("Cuba", "Guyana", "Iran (Islamic Republic of)"))

# Plot the countries with <10k total cases per 100k population.
ggplot(COVID_low_spread, aes(x = Name, y = Cases.Cumulative.Per.100k)) +
  geom_bar(stat = "identity", fill = "#005b96") +
  labs(title = "Low Spread Countries",
       x = "Country",
       y = "Cumulative Cases Per 100K Population") +
  ylim(0, 80000) +
  theme_minimal()
```

Row {data-height=125}
-----------------------------------------------------------------------

### Total Deaths

```{r valueboxes_total_deaths}
valueBox(value = "7,057,145",
         caption = "Total Global Deaths",
         icon = "ion-alert-circled",
         color = "#b3cde0")

```

### Total Deaths per 100k Population  

```{r valueboxes_total_deaths_per_100k}
valueBox(value = "29,394",
         caption = "Total Global Deaths per 100k Population",
         icon = "ion-alert-circled",
         color = "#b3cde0")

```

Row {data-height=450}
-----------------------------------------------------------------------

### High Mortality Countries 

```{r high mortality countries}
# Select three countries from the top 10 countries with the highest number of total deaths per 100K population.
# Arrange the Deaths.Cumulative.Per.100k column from descending and isolate the top 10 countries. 
COVID_high_mortality <- COVID_clean %>%
  arrange(desc(Deaths.Cumulative.Per.100k)) %>% 
  head(11) # Filter for the top 11 entries because Global is also included in the top Deaths.Cumulative.Per.100k

# The countries selected to represent the countries with the highest number of total deaths per 100k population are 
# Peru, Hungary, and Bosnia and Herzegovina. 
COVID_high_mortality <- COVID_high_mortality %>%
  filter(Name %in% c("Peru", "Hungary", "Bosnia and Herzegovina"))

# Plot the countries with one of the highest number of total death per 100k population. 
ggplot(COVID_high_mortality, aes(x = Name, y = Deaths.Cumulative.Per.100k)) +
  geom_bar(stat = "identity", fill = "#005b96") +
  labs(title = "High Mortality Countries",
       x = "Country",
       y = "Cumulative Deaths Per 100K Population") +
  ylim(0, 800) +
  theme_minimal()
```

### Low Mortality Countries 

```{r low mortality countries}

# Select three other countries where number of total deaths per 100K population is less than 250. 
# Filter Deaths.Cumulative.Per.100k with less than 250 deaths and arrange in descending order.
COVID_low_mortality <- COVID_clean %>%
  filter(Deaths.Cumulative.Per.100k < 250) %>%
  arrange(desc(Deaths.Cumulative.Per.100k))

# The countries selected to represent the countries with <10,000 deaths per 100k population are 
# Guam, Bahamas, Germany
COVID_low_mortality <- COVID_low_mortality %>% 
  filter(Name %in% c("Guam", "Bahamas", "Germany"))

# Plot the countries with <10k total death per 100k population.
ggplot(COVID_low_mortality, aes(x = Name, y = Deaths.Cumulative.Per.100k)) +
  geom_bar(stat = "identity", fill = "#005b96") +
  labs(title = "Low Mortality Countries",
       x = "Country",
       y = "Cumulative Deaths Per 100K Population") +
  ylim(0, 800) +
  theme_minimal()
```

Country Indicators
=======================================================================

```{r API}
# Extract demographic and socioeconomic indicator from World Bank API
# Build query
base <- "https://api.worldbank.org/v2"
endpoint <- "/country/AUT;KOR;CYP;GUY;CUB;IRN;PER;HUN;BIH;BHS;DEU;GUM"
query <- "/indicator/SP.POP.TOTL;EN.POP.DNST;NY.GDP.MKTP.CD;NY.GNP.MKTP.CD;SP.DYN.LE00.IN;SI.POV.NAHC;SI.POV.GINI;SE.ADT.LITR.ZS;NY.ADJ.NNTY.PC.CD;SP.DYN.CBRT.IN;SP.DYN.CDRT.IN;SP.POP.GROW;SP.URB.TOTL.IN.ZS;SP.RUR.TOTL.ZS"
output_format <- "?format=json&per_page=5000&date=2020:2022&source=2"

# Combine all parts of the query to produce a call
call <- paste0(base, endpoint, query, output_format)

# Get info from call and check status
get_data <- GET(call)

# Extract content from the request
get_data_text <- content(get_data, "text")

# Convert JSON file into an R object
get_data_json <- fromJSON(get_data_text, flatten = T)

# Converted information to dataframe
socioecon_df <- get_data_json[2][[1]]

# Renamed column names and select relevant columns
socioecon_df <- socioecon_df %>% 
  rename(
    country_iso = countryiso3code,
    year = date,
    socioecon_id = indicator.id,
    socioecon_indicator = indicator.value,
    country = country.value
    ) %>% 
  select(country, country_iso, year, socioecon_id, socioecon_indicator, value)

# Renamed values in socioeconomic indicators dataframe to make pivoting dataframe easier
socioecon_df$country[which(socioecon_df$country == "Bahamas, The")] <- "Bahamas"
socioecon_df$country[which(socioecon_df$country == "Iran, Islamic Rep.")] <- "Iran (Islamic Republic of)"
socioecon_df$country[which(socioecon_df$country == "Korea, Rep.")] <- "Republic of Korea"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Population, total")] <- "pop_total"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Population density (people per sq. km of land area)")] <- "pop_density"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "GDP (current US$)")] <- "gdp"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "GNI (current US$)")] <- "gni"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Life expectancy at birth, total (years)")] <- "life_expectancy"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Poverty headcount ratio at national poverty lines (% of population)")] <- "poverty_ratio"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Gini index")] <- "gini"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Literacy rate, adult total (% of people ages 15 and above)")] <- "literacy_rate"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Adjusted net national income per capita (current US$)")] <- "national_income_capita"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Birth rate, crude (per 1,000 people)")] <- "birth_rate"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Death rate, crude (per 1,000 people)")] <- "death_rate"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Population growth (annual %)")] <- "pop_growth"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Urban population (% of total population)")] <- "urban_pop"
socioecon_df$socioecon_indicator[which(socioecon_df$socioecon_indicator == "Rural population (% of total population)")] <- "rural_pop"

# Cleaning up dataframe containing socioeconomic indicators such that each indicator has its own column.
cleaned_socioecon <- pivot_wider(socioecon_df, id_cols = country:year, names_from = socioecon_indicator, values_from = value)
cleaned_socioecon <- cleaned_socioecon %>%
  arrange(country, year)

```

Row {data-height=50}
-----------------------------------------------------------------------
```{r}
valueBox(value = "Population Indicators",
         caption = "Data from World Bank 2024.",
         icon = "fa-solid fa-people-group",
         color = "#084b83")
```

Row {.tabset .tabset-fade}
-------------------------------------

### Total Population
```{r}
# Plot total population for all countries

pop_tot_chart <- ggplot(cleaned_socioecon, 
       aes(x = pop_total, y = reorder(country, pop_total), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Population Total by Country (2020-2022)",
       x = "Total Population",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  scale_x_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE)) +
  theme_minimal() +
  theme(legend.position = "top")
ggplotly(pop_tot_chart)
```

### Population Density
```{r}
# Plot population density for all countries
# No population density for 2022.

pop_dens_chart <- ggplot(cleaned_socioecon %>% filter(year != 2022), 
       aes(x = pop_density, y = reorder(country, pop_density), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Population Density by Country (per sq. km) (2020-2021)",
       x = "Population Density (per sq. km)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd"),
                     name = "Year") +
  theme_minimal() +
  theme(legend.position = "top")
ggplotly(pop_dens_chart)
```


### Urban Population (%)
```{r}

# Plot urban population % for all countries
urban_pop_chart <- ggplot(cleaned_socioecon %>% filter(!is.na(urban_pop)), 
       aes(x = urban_pop, y = reorder(country, urban_pop), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Urban Population As a Percent of Population by Country (2020-2022)",
       x = "Urban Population (%)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  scale_x_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE)) +
  theme_minimal() +
  theme(legend.position = "top")
ggplotly(urban_pop_chart)
```

### Rural population (%)
```{r}

# Plot rural population % for all countries
ggplot(cleaned_socioecon %>% filter(!is.na(rural_pop)), 
       aes(x = rural_pop, y = reorder(country, rural_pop), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Rural Population As a Percent of Population by Country (2020-2022)",
       x = "Rural Population (%)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  scale_x_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE)) +
  theme_minimal() +
  theme(legend.position = "top")
```

### Birth Rate
```{r}

# Plot birth rate for all countries
ggplot(cleaned_socioecon %>% filter(!is.na(birth_rate)), 
       aes(x = birth_rate, y = reorder(country, birth_rate), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Crude Birth Rate per 1000 People by Country (2020-2022)",
       x = "Crude Birth Rate (per 1000 people)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  scale_x_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE)) +
  theme_minimal() +
  theme(legend.position = "top")
```

### Death Rate
```{r}

# Plot death rate for all countries
ggplot(cleaned_socioecon %>% filter(!is.na(death_rate)), 
       aes(x = death_rate, y = reorder(country, death_rate), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Crude Death Rate per 1000 People by Country (2020-2022)",
       x = "Crude Death Rate (per 1000 people)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  scale_x_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE)) +
  theme_minimal() +
  theme(legend.position = "top")
```

### Annual Population Growth (%)
```{r}

# Plot annual population growth for all countries
ggplot(cleaned_socioecon %>% filter(!is.na(pop_growth)), 
       aes(x = pop_growth, y = reorder(country, pop_growth), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Annual Population Growth by Country (2020-2022)",
       x = "Annual Population Growth (%)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  scale_x_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE)) +
  theme_minimal() +
  theme(legend.position = "top")
```

Row {data-height=50}
-----------------------------------------------------------------------
**Economic Indicators**

Row {.tabset .tabset-fade}
-------------------------------------

### GDP (current USD)
```{r}

# Plot GDP for all countries
ggplot(cleaned_socioecon %>% filter(!is.na(gdp)), 
       aes(x = gdp, 
           y = reorder(country, gdp), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Gross Domestic Product (GDP) in Current USD by Country (2020-2022)",
       x = "GDP (in USD)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  theme_minimal() +
  theme(legend.position = "top")
```

### GNI (current USD)
```{r}

# Plot GNI for all countries
ggplot(cleaned_socioecon %>% filter(!is.na(gni)), 
       aes(x = gni, 
           y = reorder(country, gni), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Gross National Income (GNI) in Current USD by Country (2020-2022)",
       x = "GNI (in USD)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  theme_minimal() +
  theme(legend.position = "top")
```

### Adjusted Net National Income per Capita (current USD)
```{r}

# Plot Net National Income Per Capita for all countries
ggplot(cleaned_socioecon %>% filter(!is.na(national_income_capita)), 
       aes(x = national_income_capita / 1e3, 
           y = reorder(country, national_income_capita), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Adjusted Net National Income per Capita (current USD) by Country (2020-2022)",
       x = "Income per Capita (in USD Thousands)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  scale_x_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE)) +
  theme_minimal() +
  theme(legend.position = "top")
```

### Poverty Headcount Ratio
```{r}

# Plot poverty headcount ratio for all countries
ggplot(cleaned_socioecon %>% filter(!is.na(poverty_ratio)), 
       aes(x = poverty_ratio, 
           y = reorder(country, poverty_ratio), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Poverty Headcount Ratio at National Poverty Line (% of Population) by Country (2020-2022)",
       x = "Poverty Headcount Ratio (%)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  theme_minimal() +
  theme(legend.position = "top")
```

Row {data-height=50}
-----------------------------------------------------------------------
**Social Indicators**

Row {.tabset .tabset-fade}
-------------------------------------

### Life Expectancy 
```{r}

# Plot life expectancy for all countries
ggplot(cleaned_socioecon %>% filter(!is.na(life_expectancy)), 
       aes(x = life_expectancy, 
           y = reorder(country, life_expectancy), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Life Expectancy At Birth by Country (2020-2022)",
       x = "Life Expectancy (Years)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  theme_minimal() +
  theme(legend.position = "top")
```

### GINI Index
```{r}

# Plot GINI index for all countries
ggplot(cleaned_socioecon %>% filter(!is.na(gini)), 
       aes(x = gini, 
           y = reorder(country, gini), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "GINI Index by Country (2020-2022)",
       x = "GINI Index",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  theme_minimal() +
  theme(legend.position = "top")
```

### Literacy Rate
```{r}

# Plot literacy rate for all countries
ggplot(cleaned_socioecon %>% filter(!is.na(literacy_rate)), 
       aes(x = literacy_rate, 
           y = reorder(country, literacy_rate), fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Adult Literacy Rate (% of People Ages 15 and Above) by Country (2020-2022)",
       x = "Literacy Rate (%)",
       y = "Country") +
  scale_fill_manual(values = c("2020" = "#bbe6e4", 
                                "2021" = "#42bfdd", 
                                "2022" = "#084b83"),
                     name = "Year") +
  theme_minimal() +
  theme(legend.position = "top")
```

COVID-19 Analysis: 2020-2022 Overview
=======================================================================
```{r, include = FALSE}
# Import covid data with dates
covid_dates <- read.csv("WHO-COVID-19-global-data.csv")

# Filtered covid data with dates by countries of interest.
covid_dates_countries <- covid_dates %>%
  filter(Country %in% c("Austria", "Bahamas", "Bosnia and Herzegovina", "Cuba", "Cyprus", "Germany", "Guam", "Guyana", "Hungary", "Iran (Islamic Republic of)", "Republic of Korea", "Peru"))

# Converted dates in covid data with dates to date format.
covid_dates_countries$Date_reported <- as.POSIXct(covid_dates_countries$Date_reported)
# Filtered observations between start of 2020 to end of 2022.
covid_dates_countries_dates <- covid_dates_countries %>%
  filter(between(Date_reported,as.Date("2020-01-01"),as.Date("2022-12-31")))

# Filtered API data by year and population data, then alphabetizing.
country_population_2020 <- cleaned_socioecon %>%
  select(country, pop_total, year) %>%
  filter(year %in% c("2020")) %>%
  arrange(country)

country_population_2021 <- cleaned_socioecon %>%
  select(country, pop_total, year) %>%
  filter(year %in% c("2021")) %>% 
  arrange(country)

country_population_2022 <- cleaned_socioecon %>%
  select(country, pop_total, year) %>%
  filter(year %in% c("2022")) %>%
  arrange(country)

# Prevalence in 2020 = Confirmed Cases (2020) / Population (2020)
covid_dates_2020 <- covid_dates_countries_dates %>%
  filter(between(Date_reported,as.Date("2020-01-01"),as.Date("2020-12-31"))) %>%
  group_by(Country) %>%
  summarize(cases_2020 = sum(New_cases, na.rm = T))

covid_prevalence_2020 <- covid_dates_2020
prevalence_2020 <- covid_dates_2020$cases_2020 / country_population_2020$pop_total
covid_prevalence_2020$population_2020 <- country_population_2020$pop_total
covid_prevalence_2020$prevalence_2020 <- prevalence_2020
covid_prevalence_2020$prevalence_2020_percent <- covid_prevalence_2020$prevalence_2020*100

# Prevalence in 2021 = Confirmed Cases (2021) / Population (2021)
covid_dates_2021 <- covid_dates_countries_dates %>%
  filter(between(Date_reported,as.Date("2021-01-01"),as.Date("2021-12-31"))) %>%
  group_by(Country) %>%
  summarize(cases_2021 = sum(New_cases, na.rm = T))

covid_prevalence_2021 <- covid_dates_2021
prevalence_2021 <- covid_dates_2021$cases_2021 / country_population_2021$pop_total
covid_prevalence_2021$population_2021 <- country_population_2021$pop_total
covid_prevalence_2021$prevalence_2021 <- prevalence_2021
covid_prevalence_2021$prevalence_2021_percent <- covid_prevalence_2021$prevalence_2021*100

# Prevalence in 2022 = Confirmed Cases (2022) / Population (2022)
covid_dates_2022 <- covid_dates_countries_dates %>%
  filter(between(Date_reported,as.Date("2022-01-01"),as.Date("2022-12-31"))) %>%
  group_by(Country) %>%
  summarize(cases_2022 = sum(New_cases, na.rm = T))

covid_prevalence_2022 <- covid_dates_2022
prevalence_2022 <- covid_dates_2022$cases_2022 / country_population_2022$pop_total
covid_prevalence_2022$population_2022 <- country_population_2022$pop_total
covid_prevalence_2022$prevalence_2022 <- prevalence_2022
covid_prevalence_2022$prevalence_2022_percent <- covid_prevalence_2022$prevalence_2022*100

# Average Prevalence over 2020-2022 = Avg()
average_prevalence <- as.data.frame(covid_prevalence_2020$Country)
average_prevalence$prevalence_2020 <- covid_prevalence_2020$prevalence_2020
average_prevalence$prevalence_2021 <- covid_prevalence_2021$prevalence_2021
average_prevalence$prevalence_2022 <- covid_prevalence_2022$prevalence_2022

average_prevalence <- average_prevalence %>%
  rename("Country" = "covid_prevalence_2020$Country") %>%
  mutate(avg_prevalence = (prevalence_2020 + prevalence_2021 + prevalence_2022)/3)
average_prevalence$avg_prevalence_percent <- average_prevalence$avg_prevalence*100
```
```{r, include=FALSE}
#### Case Fatality Rate ####
# CFR in 2020 = Confirmed Deaths (2020) / Confirmed Cases (2020)
covid_deaths_2020 <- covid_dates_countries_dates %>%
  filter(between(Date_reported,as.Date("2020-01-01"),as.Date("2020-12-31"))) %>%
  group_by(Country) %>%
  summarize(cases_2020 = sum(New_cases, na.rm = T),
            deaths_2020 = sum(New_deaths, na.rm = T))

covid_cfr_2020 <- covid_deaths_2020
covid_cfr_2020$cfr_2020 <- covid_cfr_2020$deaths_2020 / covid_cfr_2020$cases_2020
covid_cfr_2020$cfr_2020_percent <- covid_cfr_2020$cfr_2020*100

# CFR in 2021 = Confirmed Deaths (2021) / Confirmed Cases (2021)
covid_deaths_2021 <- covid_dates_countries_dates %>%
  filter(between(Date_reported,as.Date("2021-01-01"),as.Date("2021-12-31"))) %>%
  group_by(Country) %>%
  summarize(cases_2021 = sum(New_cases, na.rm = T),
            deaths_2021 = sum(New_deaths, na.rm = T))

covid_cfr_2021 <- covid_deaths_2021
covid_cfr_2021$cfr_2021 <- covid_cfr_2021$deaths_2021 / covid_cfr_2021$cases_2021
covid_cfr_2021$cfr_2021_percent <- covid_cfr_2021$cfr_2021*100

# CFR in 2022 = Confirmed Deaths (2022) / Confirmed Cases (2022)
covid_deaths_2022 <- covid_dates_countries_dates %>%
  filter(between(Date_reported,as.Date("2022-01-01"),as.Date("2022-12-31"))) %>%
  group_by(Country) %>%
  summarize(cases_2022 = sum(New_cases, na.rm = T),
            deaths_2022 = sum(New_deaths, na.rm = T))

covid_cfr_2022 <- covid_deaths_2022
covid_cfr_2022$cfr_2022 <- covid_cfr_2022$deaths_2022 / covid_cfr_2022$cases_2022
covid_cfr_2022$cfr_2022_percent <- covid_cfr_2022$cfr_2022*100

# Average CFR over 2020-2022 = Avg()
average_cfr <- as.data.frame(covid_cfr_2020$Country)
average_cfr$cfr_2020 <- covid_cfr_2020$cfr_2020
average_cfr$cfr_2021 <- covid_cfr_2021$cfr_2021
average_cfr$cfr_2022 <- covid_cfr_2022$cfr_2022

average_cfr <- average_cfr %>%
  rename("Country" = "covid_cfr_2020$Country") %>%
  mutate(avg_cfr = (cfr_2020 + cfr_2021 + cfr_2022)/3)
average_cfr$avg_cfr_percent <- average_cfr$avg_cfr*100

```
```{r}
#### Mortality Rate ####
# MR in 2020 = Confirmed Deaths (2020) / Population (2020)
covid_mortality_2020 <- covid_dates_countries_dates %>%
  filter(between(Date_reported,as.Date("2020-01-01"),as.Date("2020-12-31"))) %>%
  group_by(Country) %>%
  summarize(deaths_2020 = sum(New_deaths, na.rm = T))

covid_mr_2020 <- covid_mortality_2020
mr_2020 <- covid_mr_2020$deaths_2020 / country_population_2020$pop_total
covid_mr_2020$population_2020 <- country_population_2020$pop_total
covid_mr_2020$mr_2020 <- mr_2020
covid_mr_2020$mr_2020_percent <- covid_mr_2020$mr_2020*100

# MR in 2021 = Confirmed Deaths (2021) / Population (2021)
covid_mortality_2021 <- covid_dates_countries_dates %>%
  filter(between(Date_reported,as.Date("2021-01-01"),as.Date("2021-12-31"))) %>%
  group_by(Country) %>%
  summarize(deaths_2021 = sum(New_deaths, na.rm = T))

covid_mr_2021 <- covid_mortality_2021
mr_2021 <- covid_mr_2021$deaths_2021 / country_population_2021$pop_total
covid_mr_2021$population_2021 <- country_population_2021$pop_total
covid_mr_2021$mr_2021 <- mr_2021
covid_mr_2021$mr_2021_percent <- covid_mr_2021$mr_2021*100

# MR in 2022 = Confirmed Deaths (2022) / Population (2022)
covid_mortality_2022 <- covid_dates_countries_dates %>%
  filter(between(Date_reported,as.Date("2022-01-01"),as.Date("2022-12-31"))) %>%
  group_by(Country) %>%
  summarize(deaths_2022 = sum(New_deaths, na.rm = T))

covid_mr_2022 <- covid_mortality_2022
mr_2022 <- covid_mr_2022$deaths_2022 / country_population_2022$pop_total
covid_mr_2022$population_2022 <- country_population_2022$pop_total
covid_mr_2022$mr_2022 <- mr_2022
covid_mr_2022$mr_2022_percent <- covid_mr_2022$mr_2022*100

# Average MR over 2020-2022 = Avg()
average_mr <- as.data.frame(covid_mr_2020$Country)
average_mr$mr_2020 <- covid_mr_2020$mr_2020
average_mr$mr_2021 <- covid_mr_2021$mr_2021
average_mr$mr_2022 <- covid_mr_2022$mr_2022

average_mr <- average_mr %>%
  rename("Country" = "covid_mr_2020$Country") %>%
  mutate(avg_mr = (mr_2020 + mr_2021 + mr_2022)/3)
average_mr$avg_mr_percent <- average_mr$avg_mr*100

```

Row {.tabset .tabset-fade}
-------------------------------------
### Prevalence

```{r, fig.width=10, fig.height=5}

# Reshape data to long format for plotting
prevalence_long <- average_prevalence %>%
  pivot_longer(cols = starts_with("prevalence_"), 
               names_to = "year", 
               values_to = "prevalence") %>%
  mutate(year = case_when(
    year == "prevalence_2020" ~ "2020",
    year == "prevalence_2021" ~ "2021",
    year == "prevalence_2022" ~ "2022"
  ),
  prevalence_percent = prevalence*100)

# Line plot for prevalence over years
ggplot(prevalence_long, aes(x = year, 
                            y = prevalence_percent, 
                            group = Country, 
                            color = Country)) +
  geom_line(linewidth = 1) +
  geom_point(size = 1) +
  labs(title = "COVID-19 Prevalence Over Years 2020-2022",
       x = "Year",
       y = "Prevalence",
       color = "Country") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

### Case Fatality Rate
```{r, fig.width=10, fig.height=5}

# Reshape data to long format for plotting
cfr_long <- average_cfr %>%
  pivot_longer(cols = starts_with("cfr_"), 
               names_to = "year", 
               values_to = "cfr") %>%
  mutate(year = case_when(
    year == "cfr_2020" ~ "2020",
    year == "cfr_2021" ~ "2021",
    year == "cfr_2022" ~ "2022"
  ),
  cfr_percent = cfr*100)

# Line plot for prevalence over years
ggplot(cfr_long, aes(x = year, y = cfr_percent, group = Country, color = Country)) +
  geom_line(linewidth = 1) +
  geom_point(size = 1) +
  labs(title = "COVID-19 Case Fatality Rate Over Years 2020-2022",
       x = "Year",
       y = "Case Fatality Rate",
       color = "Country") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

### Mortality Rate
```{r, fig.width=10, fig.height=5}

# Reshape data to long format for plotting
mortality_long <- average_mr %>%
  pivot_longer(cols = starts_with("mr_"), 
               names_to = "year", 
               values_to = "mr") %>%
  mutate(year = case_when(
    year == "mr_2020" ~ "2020",
    year == "mr_2021" ~ "2021",
    year == "mr_2022" ~ "2022"
  ),
  mr_percent = mr*100)

# Line plot for prevalence over years
ggplot(mortality_long, aes(x = year, y = mr_percent, group = Country, color = Country)) +
  geom_line(linewidth = 1) +
  geom_point(size = 1) +
  labs(title = "COVID-19 Mortality Rate Over Years 2020-2022",
       x = "Year",
       y = "Mortality Rate",
       color = "Country") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

Row {.tabset .tabset-fade}
-------------------------------------
### Average Prevalence
```{r}
avg_prev <- prevalence_long %>%
  select(Country, avg_prevalence, avg_prevalence_percent) %>%
  distinct() %>%
  mutate(
    avg_prevalence = round(avg_prevalence, 4),
    avg_prevalence_percent = round(avg_prevalence_percent, 4)
  ) %>%
  rename(
    "Average Prevalence Proportion" = avg_prevalence,
    "Average Prevalence (%)" = avg_prevalence_percent
  )
datatable(avg_prev, options = list(pageLength = 6))
```
### Average Case Fatality Rate
```{r}
avg_cfr <- cfr_long %>%
  select(Country, avg_cfr, avg_cfr_percent) %>%
  distinct() %>%
  mutate(
    avg_cfr = round(avg_cfr, 4),
    avg_cfr_percent = round(avg_cfr_percent, 4)
  ) %>%
  rename(
    "Average Case Fatality Proportion" = avg_cfr,
    "Average Case Fatality (%)" = avg_cfr_percent
  )
datatable(avg_cfr, options = list(pageLength = 6))
```
### Average Mortality Rate
```{r}
avg_mortality <- mortality_long %>%
  select(Country, avg_mr, avg_mr_percent) %>%
  distinct() %>%
  mutate(
    avg_mr = round(avg_mr, 4),
    avg_mr_percent = round(avg_mr_percent, 4)
  ) %>%
  rename(
    "Average Mortality Proportion" = avg_mr,
    "Average Mortality (%)" = avg_mr_percent
  )
datatable(avg_mortality, options = list(pageLength = 6))
```
Row {data-height=50}
-----------------------------------------
Data from World Bank 2024.